// Auth action types
export const AUTH_RESET = 'AUTH_RESET';
export const AUTH_ERROR_RESET = 'AUTH_ERROR_RESET';

export const AUTH_PAGE_ON = 'AUTH_PAGE_ON';
export const AUTH_PAGE_OFF = 'AUTH_PAGE_OFF';

export const USER_PAGE_ON = 'USER_PAGE_ON';
export const USER_PAGE_OFF = 'USER_PAGE_OFF';

export const AUTH_LOGIN_START = 'AUTH_LOGIN_START';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_SIGNUP_START = 'AUTH_SIGNUP_START';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const GET_PROFILE_START = 'GET_PROFILE_START';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

export const POST_PROFILE_START = 'POST_PROFILE_START';
export const POST_PROFILE_SUCCESS = 'POST_PROFILE_SUCCESS';
export const POST_PROFILE_FAIL = 'POST_PROFILE_FAIL';

export const CHANGE_PASSWORD_START = 'CHANGE_PASSWORD_START';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';



// FRONTEND
export const F_PRODUCTS_RESET = 'F_PRODUCTS_RESET';
export const F_PRODUCTS_START = 'F_PRODUCTS_START';
export const F_PRODUCTS_SUCCESS = 'F_PRODUCTS_SUCCESS';
export const F_PRODUCTS_FAIL = 'F_PRODUCTS_FAIL';

export const F_BLOG_RESET = 'F_BLOG_RESET';
export const F_BLOG_START = 'F_BLOG_START';
export const F_BLOG_SUCCESS = 'F_BLOG_SUCCESS';
export const F_BLOG_FAIL = 'F_BLOG_FAIL';

export const F_CONTACT_RESET = 'F_CONTACT_RESET';
export const F_CONTACT_START = 'F_CONTACT_START';
export const F_CONTACT_SUCCESS = 'F_CONTACT_SUCCESS';
export const F_CONTACT_FAIL = 'F_CONTACT_FAIL';

export const F_FOOTER_RESET = 'F_FOOTER_RESET';
export const F_FOOTER_START = 'F_FOOTER_START';
export const F_FOOTER_SUCCESS = 'F_FOOTER_SUCCESS';
export const F_FOOTER_FAIL = 'F_FOOTER_FAIL';



// BACKEND
export const B_PRODUCTS_RESET = 'B_PRODUCTS_RESET';
export const B_PRODUCTS_START = 'B_PRODUCTS_START';
export const B_PRODUCTS_SUCCESS = 'B_PRODUCTS_SUCCESS';
export const B_PRODUCTS_FAIL = 'B_PRODUCTS_FAIL';

export const B_BLOG_RESET = 'B_BLOG_RESET';
export const B_BLOG_START = 'B_BLOG_START';
export const B_BLOG_SUCCESS = 'B_BLOG_SUCCESS';
export const B_BLOG_FAIL = 'B_BLOG_FAIL';
